### ISSUE TITLE
error "spawn xprop ENOENT"

### ISSUE THREAD

**Issue by fkpwolf** [fkrull/vscode-gtk-dark-titlebar#1]
I got the error after install this extension, and toolbar wasn't dark.

OS: Arch Linux
VS: 1.21.1
Gnome: 3.26.2

**Comment by mpdeimos** [comment]
Had the same error, installed `xorg-xprop`

**Comment by fkrull** [comment]
(Thanks for not setting this repo to watched, Github.)

Yes, for now you'll need the `xprop` binary. On Debian, it's in the `x11-utils` package, for other distributions I don't know.

However, I've been trying to bundle xprop with the extension. That was mostly for the benefit of Flatpak installations, but it would also mean that one wouldn't have to install xprop separately.

**Comment by fkrull** [comment]
As promised, the new 1.2.0 version now bundles xprop for Linux amd64/i386/arm/arm64, which should cover most users. This was mostly for the benefit of [the Flatpak](https://flathub.org/apps/details/com.visualstudio.code), but should work equally on any other system. If there's no matching bundled binary, the system `xprop` is still used.
