### ISSUE TITLE
Add to Open VSX Registry

### ISSUE THREAD

**Issue by louwers** [fkrull/vscode-gtk-dark-titlebar#16]
Would be cool if this extention could be added to the [Open VSX Registry](https://open-vsx.org/).

**Comment by fkrull** [comment]
I don't know when I will get around to it, but it's a good idea and I absolutely want to do it.

**Comment by fkrull** [comment]
This is now done and future versions will be published to both repos.

https://open-vsx.org/extension/fkrull/gtk-dark-titlebar
