### ISSUE TITLE
Does not work for me - Error: spawn pidof ENOENT

### ISSUE THREAD

**Issue by kauaicreative** [fkrull/vscode-gtk-dark-titlebar#5]
this error after installing
spawn pidof ENOENT

Does this not work on windows? If not, should be stated.

**Comment by fkrull** [comment]
No, it doesn't work on Windows. Or MacOS. Or any desktop environment other than GNOME. It doesn't list every system that is unsupported, but it does explicitly mention GTK and GNOME, i.e. the things that *are* supported.

Frankly, if there was an extension that did this for Windows, I'd love to have it. But there isn't, and this one isn't it in any case.
