### ISSUE TITLE
_GTK_THEME_VARIANT xprop ignored on Fedora 38

### ISSUE THREAD

**Issue by subpop** [fkrull/vscode-gtk-dark-titlebar#57]
It looks like the xprop _GTK_THEME_VARIANT is ignored by clients on Fedora 38. I've verified that the property _GTK_THEME_VARIANT is set to dark:

```
[link@localhost ~]$ xprop -name 'Visual Studio Code' | grep GTK_THEME
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
```

But the window title bar is still light.

**Comment by fkrull** [comment]
Huh, thanks for the report. I'm gonna look into it, buuuuut if it doesn't work it doesn't work. Not even setting `GTK_THEME=Adwaita:dark` works, that makes the menu bar and Gtk dialogs dark, but the titlebar stays light.

I'll try and see if I can find out what changed, but maybe don't get your hopes up. Given there hasn't been a Wayland equivalent of this setting, I wouldn't be surprised if Gtk removed it on the X11 side as well. :\

**Comment by fkrull** [comment]
Ok so I think this is a consequence of https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2175. Mutter/GNOME Shell changed the way they draw window borders for X11 windows that don't draw their own window borders. There's [a followup MR](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2739#note_1610278) that has a comment mentioning that the `_GTK_THEME_VARIANT` property doesn't work any more.

I guess that means this extension has now outlived its usefulness. 🤷 Maybe it's possible to add back support for _GTK_THEME_VARIANT to Mutter, but the effort seems better spent finally fixing this upstream in VSCode.

I don't have the bandwidth for that tho, so I guess I'll add a big fat deprecation notice to the readme and get used to mismatching titlebars.

**Comment by westurner** [comment]
Is there a vscode issue for this?
- https://github.com/fkrull/vscode-gtk-dark-titlebar/blob/9ef39b6b24d97741cdd00b36218834f394558b19/src/setGtkThemeVariant.ts#L53-L55


Changing `window.titleBarStyle` from `native` to `custom` seems to hide the light File menu titlebar which seems to work around the problem?
```json
"window.titleBarStyle": "custom"
```

That could just be the default in the Flatpak repack of vscode?

**Comment by westurner** [comment]
FWIW it looks like `flatpak install flathub com.vscodium.codium` installs `org.gtk.Gtk3theme.Adwaita-dark`, but IDK where that's specified if not in the flatpak?

- https://github.com/search?q=repo%3Aflathub%2Fcom.vscodium.codium%20adwaita&type=code ?
- https://github.com/search?q=repo%3AVSCodium%2Fvscodium+adwaita&type=issues

One workaround for missing Adwaita-dark theme in the flatpak is to instead install vscode in a container (possibly managed with `toolbox` to mount `$HOME` within the container with the correct uid; instead or in addition to Dev Containers / ). But the vscode flatpak should be enough to host a lightweight vscode frontend with "Remote " extensions I need to catalog the links of anyway; and There are probably not integration tests for these extensions which support host isolation, that may be run in the flatpak:

- Name: Remote Development
  - Src: https://github.com/Microsoft/vscode-remote-release
    > Visual Studio Code Remote Development: Open any folder in WSL, in a Docker container, or on a remote machine using SSH and take advantage of VS Code's full feature set.
  - `ms-vscode-remote.vscode-remote-extensionpack`
  - https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack
    - Name: Dev Containers
      - `ms-vscode-remote.remote-containers`
      - https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
    - Name: Remote - SSH
      - `ms-vscode-remote.remote-ssh`
      - https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

- .
  - .
    - .
      - Name: Remote - Kubernetes
        - Id: okteto.remote-kubernetes
        - https://marketplace.visualstudio.com/items?itemName=okteto.remote-kubernetes
      - https://github.com/loft-sh/devpod
        - https://devpod.sh/docs/getting-started/quickstart-vscode

**Comment by fkrull** [comment]
> Is there a vscode issue for this?

From a brief search:
* VSCode issue: https://github.com/microsoft/vscode/issues/130974
* Electron PR: https://github.com/electron/electron/pull/38977
* another possibly related Electron issue: https://github.com/electron/electron/issues/33635
* another VSCode issue: https://github.com/microsoft/vscode/issues/181831
* and another one: https://github.com/microsoft/vscode/issues/146804

There's probably more tbh. Turns out Chromium's OS integration on Linux kinda sucks ass. :shrug: 

> Changing window.titleBarStyle from native to custom seems to hide the light File menu titlebar which seems to work around the problem?

Yeah, that makes VSCode draw the titlebars which means they match the VSCode theme. The downside is that they look and act different from either WM-drawn decorations for GTK client-side decorations.

> FWIW it looks like flatpak install flathub com.vscodium.codium installs org.gtk.Gtk3theme.Adwaita-dark, but IDK where that's specified if not in the flatpak?

I think that's Flatpak's theme installation magic. I believe it determines what theme you have set and installs the corresponding extension from Flathub.
