### ISSUE TITLE
I can't get it installed on my win10-vs code

### ISSUE THREAD

**Issue by KangOxford** [fkrull/vscode-gtk-dark-titlebar#8]
![image](https://user-images.githubusercontent.com/37290277/42382493-08734486-8167-11e8-9d41-ac86f12906ae.png)
although I have changed the settings , but it still seems that the bar on the top is light rather than a dark one.

**Comment by KangOxford** [comment]
![image](https://user-images.githubusercontent.com/37290277/42382698-b0cc8494-8167-11e8-86f4-1ce1aa678d5d.png)
more info

**Comment by KangOxford** [comment]
is this only works for macos?

**Comment by fkrull** [comment]
It only works on Linux.
