### ISSUE TITLE
spawn pidof ENOENT error

### ISSUE THREAD

**Issue by gerardo-galvan** [fkrull/vscode-gtk-dark-titlebar#9]
Tittle bar remains white and doesn't turn dark. I get error, "spawn pidof ENOENT"

**Comment by fkrull** [comment]
Are you on Windows? This extension doesn't work on Windows.

If not: what Linux distribution are you using and how did you install VS Code? If you just type `pidof` in a terminal, what happens?

**Comment by gerardo-galvan** [comment]
Windows 10. Thanks! I figured I had to change it system wide on Windows with different software.


________________________________

**Comment by fkrull** [comment]
VS Code 1.25 adds a custom title bar for Windows (and Linux) that honours the theme: https://code.visualstudio.com/updates/v1_25#_custom-title-bar-and-menus-for-windowslinux
